- .vscode/settings.json
- removes .vscode from being tracked
> removes .vscode

- src/apis/index.js
- [Fix] fixes axios/apiUrl import statement
> fixes api imports

- src/apis/index.js
- just removes a header from axios config
> removes unnecessary header in api instantiation

- src/components/Navbar.js
- src/pages/Home/components/MapComponent.js
> Nav link and import

- src/actions/index.js
- src/pages/BusinessList/index.js
> Deploy fix

- src/pages/Business/index.js
- src/reducers/singleBusinessReducer.js
> [WIP] Single Business View

- package.json
- src/pages/Home/components/SearchBar.js
- yarn.lock
The homepage search component redirects to the business list component and prepopulates the inputs
> Homepage search functionality

- src/pages/Home/components/SearchBar.js
Reverts minor change from previous PR - Tested and ready to go. 
> Reverts to entire address

- src/pages/Home/components/SearchBar.js
> Yelp logo in homepage

- src/components/Navbar.js
- src/pages/Home/components/SearchBar.js
> Navbar Styling

- src/pages/BusinessList/index.js
> Pagination

- src/pages/Home/components/SearchBar.js
- src/reducers/searchReducer.js
Adds new hero image to better reflect app goals
> New hero image

- src/components/Navbar.js
- src/pages/Business/components/ReviewForm.js
- src/pages/Profile/index.js
- src/pages/SignIn/index.js
- src/reducers/searchReducer.js
> small patch to navlinks

- src/pages/Business/index.js
- src/pages/BusinessList/index.js
> argh more tweaks to navlinks

- src/pages/Business/components/ReviewForm.js
- src/pages/Business/components/Reviews.js
> debug statements

- src/reducers/singleBusinessReducer.js
- [X ] Bug fix (non-breaking change which fixes an issue)
> Singlereducer fix

- src/pages/Home/components/SearchBar.js
> hotfix: fixes undefined on homepage search term 🚑

- src/actions/index.js
- src/containers/SearchFilter.js
- src/reducers/searchReducer.js
> draft search filter functionality

- src/containers/SearchFilter.js
> Search filter button

- src/containers/Map.js
- src/pages/BusinessList/index.js
> ipad business list styling refactor ✨

- src/actions/index.js
- src/config/index.js
- src/pages/Business/components/AddBusinessForm.js
- src/pages/Business/components/Reviews.js
> Implements Formik on CreateBusinessView

- src/pages/Business/components/AddBusinessForm.js
- src/pages/Business/components/AddBusinessPhoto.js
- src/pages/Home/components/SearchBar.js
> ATTACHING IMAGE TO BUSINESS CREATION FORM

- src/config/index.js
- src/pages/Business/components/AddBusinessForm.js
- src/pages/Business/components/AddBusinessPhoto.js
> adds create business photo preview functionality

- src/App/index.js
> import Footer 🥾

- src/App/index.js
- src/components/Logo.js
> Fix footer

- src/pages/Business/components/ReviewPhotosInput.js
> 🚑 edit/create review changed request from patch to post for create

- src/pages/Business/components/ReviewForm.js
- src/pages/Business/index.js
- src/pages/BusinessGallery/index.js
- src/pages/BusinessList/index.js
- src/pages/Home/components/SearchBar.js
Rollsback useEffect dep array issues
> rollsback use effect dep array

- src/actions/index.js
- src/containers/Map.js
- src/containers/SearchFilter.js
- src/pages/Business/components/AddBusinessForm.js
- src/pages/Business/components/AddBusinessPhoto.js
- src/pages/Business/components/ReviewForm.js
- src/pages/Business/index.js
- src/pages/BusinessGallery/index.js
- src/pages/BusinessList/index.js
- src/pages/Home/components/SearchBar.js
- src/reducers/mapReducer.js
> Gallery styling

- src/actions/index.js
- src/containers/Map.js
- src/containers/SearchFilter.js
- src/pages/Business/components/ReviewForm.js
- src/pages/Business/index.js
- src/pages/BusinessGallery/index.js
- src/pages/BusinessList/index.js
- src/pages/Home/components/SearchBar.js
- src/reducers/mapReducer.js
> Search filter location

- src/actions/index.js
- src/containers/Map.js
- src/containers/SearchFilter.js
- src/pages/Business/components/AddBusinessForm.js
- src/pages/Business/components/AddBusinessPhoto.js
- src/pages/Business/components/ReviewForm.js
- src/pages/Business/index.js
- src/pages/BusinessGallery/index.js
- src/pages/BusinessList/index.js
- src/pages/Home/components/SearchBar.js
- src/reducers/mapReducer.js
> Style business img preview

- src/config/index.js
- src/pages/EditProfile/index.js
-[X] Removes create business placeholder data
> removes placeholder data

- src/components/Dropdown.js
- src/containers/SearchBar.js
> implements close onclickoutside on autocomplete dropdown

- src/containers/SearchBar.js
> fixes autocomplete query on all views

- src/pages/BusinessList/index.js
> darn one sticky depency warning; revert to render correctly

- src/pages/BusinessGallery/index.js
- src/pages/BusinessList/index.js
> business gallery component touch up

- src/pages/BusinessList/index.js
> missing comma

- src/pages/Profile/components/ReviewCard.js
> User reviews

- src/components/ErrorBoundary.js
-[X] onCatch error, play tetris 😆 
> onCatch error, play Tetris

- src/components/AvatarPopup.js
- src/pages/EditProfile/components/ProfileForm.js
- src/pages/Profile/components/UserProfile.js
- src/pages/Profile/index.js
- src/reducers/userReducer.js
> adds city and state
